#!/usr/bin/env bash
#
# compare-table.sh — Compare a single table's Rust output to a reference.
# Default: MD5-only against MD5SUMS. --full: byte-for-byte (MD5 + diff).
#
# Please see print_usage() below for details.

set -euo pipefail

print_usage() {
    cat << 'EOF'
compare-table.sh — Compare a single table's Rust output to a reference.

By default it compares the MD5 hash of the Rust output against the
expected hash values in tests/fixtures/tpcds/scale-N-{trino,c}/MD5SUMS.

Pass --full to instead compare byte-for-byte against the actual reference
output (MD5 + diff). This is slower but produces a row-level diff when
something does not match. Generate the fixture first with
./scripts/tpcds/generate-fixtures.sh.

Two reference implementations are supported, selected by --compat:
    --compat trino  (default)  Java / Trino reference
                               (MD5SUMS: tests/fixtures/tpcds/scale-N-trino/MD5SUMS;
                                fixtures: same dir, --full only)
    --compat c                 C dsdgen reference
                               (MD5SUMS: tests/fixtures/tpcds/scale-N-c/MD5SUMS;
                                fixtures: same dir, --full only)

Usage:
    compare-table.sh TABLE_NAME [OPTIONS]

Arguments:
    TABLE_NAME      Name of the table to compare (e.g. call_center).

Options:
    --scale N           Scale factor (default: 1).
    --compat trino|c    Reference implementation (default: trino).
    --full              Compare byte-for-byte against the full .dat fixture
                        (MD5 + diff). Requires the fixture to exist locally.
    --quiet             Quiet mode (minimal output).
    --help              Show this help message.

Examples:
    compare-table.sh call_center                  # MD5-only, vs. Trino, scale 1
    compare-table.sh reason --compat c            # MD5-only, vs. C dsdgen
    compare-table.sh inventory --scale 10 --full  # byte-for-byte, vs. Trino
    compare-table.sh customer_demographics --quiet

Exit codes:
    0 - Hashes (or full fixtures, with --full) match.
    1 - Mismatch or an error occurred.

See scripts/README.md for the full conformance-testing workflow.
EOF
    exit 0
}

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Script directory and project root
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

# Configuration (can be overridden by --scale)
SCALE_FACTOR=${TPCDS_SCALE:-1}
COMPAT=${TPCDS_COMPAT:-trino}
QUIET=0
FULL=0

# Logging functions
log_info() {
    if [[ $QUIET -eq 0 ]]; then
        echo -e "${BLUE}[INFO]${NC} $*"
    fi
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $*"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $*" >&2
}

log_diff() {
    echo -e "${YELLOW}[DIFF]${NC} $*"
}

# Returns tables are generated by their parent sales generators.
# Map returns table -> parent table (the one to generate).
get_generator_for_table() {
    local table=$1
    case $table in
        catalog_returns) echo "catalog_sales" ;;
        store_returns)   echo "store_sales" ;;
        web_returns)     echo "web_sales" ;;
        *)               echo "$table" ;;
    esac
}

# Find the unified tpcgen-cli binary
find_rust_binary() {
    local target_dir

    # Detect if we're in a workspace using cargo
    if command -v cargo >/dev/null 2>&1; then
        local workspace_root
        workspace_root=$(cd "$PROJECT_ROOT" && cargo locate-project --workspace --message-format=plain 2>/dev/null | xargs dirname)

        if [[ -n "$workspace_root" && -d "$workspace_root" ]]; then
            # In a workspace - use workspace target directory
            target_dir="$workspace_root/target"
        else
            # Standalone project
            target_dir="$PROJECT_ROOT/target"
        fi
    else
        # No cargo available, fall back to PROJECT_ROOT
        target_dir="$PROJECT_ROOT/target"
    fi

    # Try release build
    local binary="$target_dir/release/tpcgen-cli"
    if [[ -f "$binary" ]]; then
        echo "$binary"
        return 0
    fi

    # Try debug build
    binary="$target_dir/debug/tpcgen-cli"
    if [[ -f "$binary" ]]; then
        echo "$binary"
        return 0
    fi

    return 1
}

# Generate table with Rust
generate_rust_table() {
    local table=$1
    local output_file=$2
    local binary
    local generator

    generator=$(get_generator_for_table "$table")

    if ! binary=$(find_rust_binary); then
        log_error "Rust binary not found"
        log_error "Build it with: cargo build --locked --release -p tpcgen-cli"
        return 1
    fi

    log_info "Generating $table with Rust..."
    log_info "Using binary: $binary tpcds dat --compat $COMPAT --tables $generator --scale-factor $SCALE_FACTOR"
    if [[ "$generator" != "$table" ]]; then
        log_info "Note: $table is generated alongside $generator"
    fi

    # Create temp directory for generation
    local temp_dir
    temp_dir=$(mktemp -d)

    # Run Rust generator with --compat, --tables, --scale-factor, and --output-dir flags
    if ! "$binary" tpcds dat --compat "$COMPAT" --tables "$generator" --scale-factor "$SCALE_FACTOR" --output-dir "$temp_dir" >/dev/null 2>&1; then
        log_error "Failed to generate $table with Rust"
        rm -rf "$temp_dir"
        return 1
    fi

    # Move generated file (table name, not generator name)
    if [[ -f "$temp_dir/${table}.dat" ]]; then
        mv "$temp_dir/${table}.dat" "$output_file"
        rm -rf "$temp_dir"
        return 0
    else
        log_error "Expected Rust output file not found: $temp_dir/${table}.dat"
        log_error "Files in temp dir: $(ls -la "$temp_dir")"
        rm -rf "$temp_dir"
        return 1
    fi
}

# Compute MD5 hash (works on both macOS and Linux)
compute_md5() {
    local file=$1
    if command -v md5sum >/dev/null 2>&1; then
        md5sum "$file" | cut -d' ' -f1
    elif command -v md5 >/dev/null 2>&1; then
        md5 -q "$file"
    else
        echo "NO_MD5"
    fi
}

# Look up the expected MD5 hash for $table in $md5sums_file.
lookup_expected_md5() {
    local md5sums_file=$1
    local table=$2
    awk -v t="${table}.dat" '$2 == t { print $1; found=1; exit } END { exit !found }' "$md5sums_file"
}

# Default (fast) comparison: check the Rust output's MD5 against the
# expected hash in MD5SUMS. Does not require the .dat fixture to be
# present locally.
compare_md5_only() {
    local md5sums_file=$1
    local rust_file=$2
    local table=$3
    local ref_label=$4

    local expected_md5
    if ! expected_md5=$(lookup_expected_md5 "$md5sums_file" "$table"); then
        log_error "No expected MD5 for $table in $md5sums_file"
        log_error "Run ./scripts/tpcds/generate-fixtures.sh --compat $COMPAT --scale $SCALE_FACTOR to refresh it."
        return 1
    fi

    local rust_rows rust_md5
    rust_rows=$(wc -l < "$rust_file" | tr -d ' ')
    rust_md5=$(compute_md5 "$rust_file")

    log_info "Rust output: $rust_rows rows"
    log_info "$ref_label expected MD5: $expected_md5"
    log_info "Rust MD5:              $rust_md5"

    if [[ "$rust_md5" == "$expected_md5" ]]; then
        log_success "✓ $table: MD5 match ($rust_rows rows, $rust_md5)"
        return 0
    fi

    log_error "✗ $table: MD5 mismatch!"
    log_error "  $ref_label expected: $expected_md5"
    log_error "  Rust:              $rust_md5"
    log_error "Re-run with --full for a row-level diff."
    return 1
}

# Full comparison: require the .dat fixture, then check MD5 and emit a
# diff on mismatch.
compare_full() {
    local ref_file=$1
    local rust_file=$2
    local table=$3
    local ref_label=$4

    log_info "Comparing outputs..."

    # Get file sizes
    local ref_size rust_size ref_rows rust_rows

    ref_size=$(du -h "$ref_file" | cut -f1)
    rust_size=$(du -h "$rust_file" | cut -f1)
    ref_rows=$(wc -l < "$ref_file" | tr -d ' ')
    rust_rows=$(wc -l < "$rust_file" | tr -d ' ')

    log_info "$ref_label fixture: $ref_rows rows, $ref_size"
    log_info "Rust output:    $rust_rows rows, $rust_size"

    # Quick check: row count must match
    if [[ "$ref_rows" != "$rust_rows" ]]; then
        log_error "Row count mismatch!"
        log_error "  $ref_label: $ref_rows rows"
        log_error "  Rust: $rust_rows rows"
        return 1
    fi

    # Compute MD5 hashes
    log_info "Computing MD5 hashes..."
    local ref_md5 rust_md5
    ref_md5=$(compute_md5 "$ref_file")
    rust_md5=$(compute_md5 "$rust_file")

    log_info "$ref_label MD5: $ref_md5"
    log_info "Rust MD5: $rust_md5"

    # Compare MD5 hashes
    if [[ "$ref_md5" == "$rust_md5" ]]; then
        log_success "✓ $table: MD5 match ($ref_rows rows, $ref_md5)"
        return 0
    else
        log_error "✗ $table: MD5 mismatch!"
        log_error "  $ref_label: $ref_md5"
        log_error "  Rust:    $rust_md5"
        log_diff "Showing first differences:"
        diff -u "$ref_file" "$rust_file" | head -30 || true
        return 1
    fi
}

# Main function
main() {
    local table=""

    # Parse arguments
    while [[ $# -gt 0 ]]; do
        case $1 in
            --scale)
                SCALE_FACTOR="$2"
                shift 2
                ;;
            --compat)
                COMPAT="$2"
                shift 2
                ;;
            --full)
                FULL=1
                shift
                ;;
            --quiet)
                QUIET=1
                shift
                ;;
            --help)
                print_usage
                ;;
            *)
                if [[ -z "$table" ]]; then
                    table=$1
                else
                    log_error "Too many arguments"
                    print_usage
                fi
                shift
                ;;
        esac
    done

    # Resolve compat mode -> fixture directory and reference label
    local ref_label
    case $COMPAT in
        trino)
            FIXTURE_DIR="$PROJECT_ROOT/tests/fixtures/tpcds/scale-${SCALE_FACTOR}-trino"
            ref_label="Trino"
            ;;
        c)
            FIXTURE_DIR="$PROJECT_ROOT/tests/fixtures/tpcds/scale-${SCALE_FACTOR}-c"
            ref_label="C dsdgen"
            ;;
        *)
            log_error "Unknown --compat value: $COMPAT (expected: trino, c)"
            exit 1
            ;;
    esac

    # Validate table argument
    if [[ -z "$table" ]]; then
        log_error "Table name required"
        print_usage
    fi

    local mode_label="MD5-only"
    [[ $FULL -eq 1 ]] && mode_label="full byte-for-byte"

    log_info "========================================="
    log_info "Table Comparison: $table ($mode_label)"
    log_info "========================================="

    local md5sums_file="$FIXTURE_DIR/MD5SUMS"
    local fixture_file="$FIXTURE_DIR/${table}.dat"

    if [[ $FULL -eq 1 ]]; then
        if [[ ! -f "$fixture_file" ]]; then
            log_error "Fixture not found: $fixture_file"
            if [[ "$COMPAT" == "c" ]]; then
                log_error "Download C reference data first: ./scripts/tpcds/generate-fixtures.sh --compat c --scale $SCALE_FACTOR"
            else
                log_error "Generate fixtures first: ./scripts/tpcds/generate-fixtures.sh $table"
            fi
            exit 1
        fi
        log_info "$ref_label fixture: $fixture_file"
    else
        if [[ ! -f "$md5sums_file" ]]; then
            log_error "MD5SUMS not found: $md5sums_file"
            log_error "Refresh it with: ./scripts/tpcds/generate-fixtures.sh --compat $COMPAT --scale $SCALE_FACTOR"
            exit 1
        fi
        log_info "$ref_label MD5SUMS: $md5sums_file"
    fi

    # Generate Rust output
    local rust_output
    rust_output=$(mktemp)

    if ! generate_rust_table "$table" "$rust_output"; then
        rm -f "$rust_output"
        exit 1
    fi

    log_info "Rust output: $rust_output (temporary)"

    # Compare
    local result=0
    if [[ $FULL -eq 1 ]]; then
        if ! compare_full "$fixture_file" "$rust_output" "$table" "$ref_label"; then
            result=1
        fi
    else
        if ! compare_md5_only "$md5sums_file" "$rust_output" "$table" "$ref_label"; then
            result=1
        fi
    fi

    # Cleanup
    rm -f "$rust_output"

    log_info "========================================="

    exit $result
}

main "$@"
