use std::fmt;
use std::str::FromStr;

/// Compatibility mode controlling which reference implementation to match.
///
/// TPC-DS has two common reference implementations: the original C `dsdgen` and the
/// Trino Java port. They diverge in a small number of places. This flag selects
/// which behaviour to replicate.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum CompatMode {
    /// Match the Trino Java implementation (default).
    ///
    /// Byte-for-byte compatible with the Trino `io.trino.tpcds` library. Use this
    /// when results need to agree with other Trino-based tooling.
    #[default]
    Trino,

    /// Match the original C `dsdgen` reference implementation.
    ///
    /// Corrects known divergences in the Java port. Use this when results need to
    /// agree with data generated by the official TPC-DS C tools.
    C,
}

impl fmt::Display for CompatMode {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            CompatMode::Trino => f.write_str("trino"),
            CompatMode::C => f.write_str("c"),
        }
    }
}

impl FromStr for CompatMode {
    type Err = String;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match value.to_ascii_lowercase().as_str() {
            "trino" => Ok(CompatMode::Trino),
            "c" => Ok(CompatMode::C),
            _ => Err(format!(
                "invalid compat mode '{value}', expected 'trino' or 'c'"
            )),
        }
    }
}
