/// Compatibility mode controlling which reference implementation to match.
///
/// TPC-DS has two common reference implementations: the original C `dsdgen` and the
/// Trino Java port. They diverge in a small number of places. This flag selects
/// which behaviour to replicate.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, clap::ValueEnum)]
pub enum CompatMode {
    /// Match the Trino Java implementation (default).
    ///
    /// Byte-for-byte compatible with the Trino `io.trino.tpcds` library. Use this
    /// when results need to agree with other Trino-based tooling.
    #[default]
    Trino,

    /// Match the original C `dsdgen` reference implementation.
    ///
    /// Corrects known divergences in the Java port. Use this when results need to
    /// agree with data generated by the official TPC-DS C tools.
    C,
}
