[package]
name = "tpcdsgen-arrow"
version = "0.1.0"
edition = "2021"
authors = ["clflushopt", "alamb"]
description = "TPC-DS data generator into Apache Arrow format"
repository = { workspace = true }
readme = "README.md"
license = "Apache-2.0"

[dependencies]
arrow = { workspace = true }
tpcdsgen = { path = "../tpcdsgen", version = "0.1.0" }

[dev-dependencies]
arrow-csv = { workspace = true }
regex = "1"
