#!/usr/bin/env bash
#
# compare-table.sh — Compare a single table's Rust output to a reference
# fixture byte-for-byte (MD5 + diff).
#
# Please see print_usage() below for details.

set -euo pipefail

print_usage() {
    cat << 'EOF'
compare-table.sh — Compare a single table's Rust output to a reference
fixture byte-for-byte (MD5 + diff).

Two reference implementations are supported, selected by --compat:
    --compat trino  (default)  Java / Trino fixtures in
                               tests/fixtures/scale-N-trino/
                               (generate with
                                ./scripts/generate-fixtures.sh)
    --compat c                 C dsdgen fixtures in
                               tests/fixtures/scale-N-c/
                               (download with
                                ./scripts/generate-fixtures.sh --compat c)

Usage:
    compare-table.sh TABLE_NAME [OPTIONS]

Arguments:
    TABLE_NAME      Name of the table to compare (e.g. call_center).

Options:
    --scale N           Scale factor (default: 1).
    --compat trino|c    Reference implementation (default: trino).
    --quiet             Quiet mode (minimal output).
    --help              Show this help message.

Examples:
    compare-table.sh call_center                  # vs. Trino, scale 1
    compare-table.sh reason --compat c            # vs. C dsdgen, scale 1
    compare-table.sh inventory --scale 10         # vs. Trino, scale 10
    compare-table.sh customer_demographics --quiet

Output example:
    [INFO] Table Comparison: call_center
    [INFO] Trino fixture: tests/fixtures/scale-1-trino/call_center.dat
    [INFO] Trino fixture: 6 rows, 4.0K
    [INFO] Rust output:   6 rows, 4.0K
    [SUCCESS] ✓ call_center: MD5 match (6 rows, cc9aab...)

Exit codes:
    0 - Tables match exactly.
    1 - Tables differ or an error occurred.

See scripts/README.md for the full conformance-testing workflow.
EOF
    exit 0
}

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Script directory and project root
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# Configuration (can be overridden by --scale)
SCALE_FACTOR=${TPCDS_SCALE:-1}
COMPAT=${TPCDS_COMPAT:-trino}
QUIET=0

# Logging functions
log_info() {
    if [[ $QUIET -eq 0 ]]; then
        echo -e "${BLUE}[INFO]${NC} $*"
    fi
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $*"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $*" >&2
}

log_diff() {
    echo -e "${YELLOW}[DIFF]${NC} $*"
}

# Returns tables are generated by their parent sales generators.
# Map returns table -> parent table (the one to generate).
get_generator_for_table() {
    local table=$1
    case $table in
        catalog_returns) echo "catalog_sales" ;;
        store_returns)   echo "store_sales" ;;
        web_returns)     echo "web_sales" ;;
        *)               echo "$table" ;;
    esac
}

# Find the unified tpcdsgen binary
find_rust_binary() {
    local target_dir

    # Detect if we're in a workspace using cargo
    if command -v cargo >/dev/null 2>&1; then
        local workspace_root
        workspace_root=$(cd "$PROJECT_ROOT" && cargo locate-project --workspace --message-format=plain 2>/dev/null | xargs dirname)

        if [[ -n "$workspace_root" && -d "$workspace_root" ]]; then
            # In a workspace - use workspace target directory
            target_dir="$workspace_root/target"
        else
            # Standalone project
            target_dir="$PROJECT_ROOT/target"
        fi
    else
        # No cargo available, fall back to PROJECT_ROOT
        target_dir="$PROJECT_ROOT/target"
    fi

    # Try release build
    local binary="$target_dir/release/tpcdsgen"
    if [[ -f "$binary" ]]; then
        echo "$binary"
        return 0
    fi

    # Try debug build
    binary="$target_dir/debug/tpcdsgen"
    if [[ -f "$binary" ]]; then
        echo "$binary"
        return 0
    fi

    return 1
}

# Generate table with Rust
generate_rust_table() {
    local table=$1
    local output_file=$2
    local binary
    local generator

    generator=$(get_generator_for_table "$table")

    if ! binary=$(find_rust_binary); then
        log_error "Rust binary not found"
        log_error "Build it with: cargo build --release"
        return 1
    fi

    log_info "Generating $table with Rust..."
    log_info "Using binary: $binary --compat $COMPAT --table $generator --scale $SCALE_FACTOR"
    if [[ "$generator" != "$table" ]]; then
        log_info "Note: $table is generated alongside $generator"
    fi

    # Create temp directory for generation
    local temp_dir
    temp_dir=$(mktemp -d)

    # Run Rust generator with --compat, --table, --scale, and --directory flags
    if ! "$binary" --compat "$COMPAT" --table "$generator" --scale "$SCALE_FACTOR" --directory "$temp_dir" >/dev/null 2>&1; then
        log_error "Failed to generate $table with Rust"
        rm -rf "$temp_dir"
        return 1
    fi

    # Move generated file (table name, not generator name)
    if [[ -f "$temp_dir/${table}.dat" ]]; then
        mv "$temp_dir/${table}.dat" "$output_file"
        rm -rf "$temp_dir"
        return 0
    else
        log_error "Expected Rust output file not found: $temp_dir/${table}.dat"
        log_error "Files in temp dir: $(ls -la "$temp_dir")"
        rm -rf "$temp_dir"
        return 1
    fi
}

# Compute MD5 hash (works on both macOS and Linux)
compute_md5() {
    local file=$1
    if command -v md5sum >/dev/null 2>&1; then
        md5sum "$file" | cut -d' ' -f1
    elif command -v md5 >/dev/null 2>&1; then
        md5 -q "$file"
    else
        echo "NO_MD5"
    fi
}

# Compare two files
compare_files() {
    local ref_file=$1
    local rust_file=$2
    local table=$3
    local ref_label=$4

    log_info "Comparing outputs..."

    # Get file sizes
    local ref_size rust_size ref_rows rust_rows

    ref_size=$(du -h "$ref_file" | cut -f1)
    rust_size=$(du -h "$rust_file" | cut -f1)
    ref_rows=$(wc -l < "$ref_file" | tr -d ' ')
    rust_rows=$(wc -l < "$rust_file" | tr -d ' ')

    log_info "$ref_label fixture: $ref_rows rows, $ref_size"
    log_info "Rust output:    $rust_rows rows, $rust_size"

    # Quick check: row count must match
    if [[ "$ref_rows" != "$rust_rows" ]]; then
        log_error "Row count mismatch!"
        log_error "  $ref_label: $ref_rows rows"
        log_error "  Rust: $rust_rows rows"
        return 1
    fi

    # Compute MD5 hashes
    log_info "Computing MD5 hashes..."
    local ref_md5 rust_md5
    ref_md5=$(compute_md5 "$ref_file")
    rust_md5=$(compute_md5 "$rust_file")

    log_info "$ref_label MD5: $ref_md5"
    log_info "Rust MD5: $rust_md5"

    # Compare MD5 hashes
    if [[ "$ref_md5" == "$rust_md5" ]]; then
        log_success "✓ $table: MD5 match ($ref_rows rows, $ref_md5)"
        return 0
    else
        log_error "✗ $table: MD5 mismatch!"
        log_error "  $ref_label: $ref_md5"
        log_error "  Rust:    $rust_md5"
        log_diff "Showing first differences:"
        diff -u "$ref_file" "$rust_file" | head -30 || true
        return 1
    fi
}

# Main function
main() {
    local table=""

    # Parse arguments
    while [[ $# -gt 0 ]]; do
        case $1 in
            --scale)
                SCALE_FACTOR="$2"
                shift 2
                ;;
            --compat)
                COMPAT="$2"
                shift 2
                ;;
            --quiet)
                QUIET=1
                shift
                ;;
            --help)
                print_usage
                ;;
            *)
                if [[ -z "$table" ]]; then
                    table=$1
                else
                    log_error "Too many arguments"
                    print_usage
                fi
                shift
                ;;
        esac
    done

    # Resolve compat mode -> fixture directory and reference label
    local ref_label
    case $COMPAT in
        trino)
            FIXTURE_DIR="$PROJECT_ROOT/tests/fixtures/scale-${SCALE_FACTOR}-trino"
            ref_label="Trino"
            ;;
        c)
            FIXTURE_DIR="$PROJECT_ROOT/tests/fixtures/scale-${SCALE_FACTOR}-c"
            ref_label="C dsdgen"
            ;;
        *)
            log_error "Unknown --compat value: $COMPAT (expected: trino, c)"
            exit 1
            ;;
    esac

    # Validate table argument
    if [[ -z "$table" ]]; then
        log_error "Table name required"
        print_usage
    fi

    log_info "========================================="
    log_info "Table Comparison: $table"
    log_info "========================================="

    # Check if fixture exists
    local fixture_file="$FIXTURE_DIR/${table}.dat"
    if [[ ! -f "$fixture_file" ]]; then
        log_error "Fixture not found: $fixture_file"
        if [[ "$COMPAT" == "c" ]]; then
            log_error "Download C reference data first: ./scripts/generate-fixtures.sh --compat c --scale $SCALE_FACTOR"
        else
            log_error "Generate fixtures first: ./scripts/generate-fixtures.sh $table"
        fi
        exit 1
    fi

    log_info "$ref_label fixture: $fixture_file"

    # Generate Rust output
    local rust_output
    rust_output=$(mktemp)

    if ! generate_rust_table "$table" "$rust_output"; then
        rm -f "$rust_output"
        exit 1
    fi

    log_info "Rust output: $rust_output (temporary)"

    # Compare files
    local result=0
    if ! compare_files "$fixture_file" "$rust_output" "$table" "$ref_label"; then
        result=1
    fi

    # Cleanup
    rm -f "$rust_output"

    log_info "========================================="

    exit $result
}

main "$@"
