//! Driving the TPC-DS row generators, shared by the DAT and CSV outputs.

use crate::progress::ProgressHandle;
use log::info;
use std::io;
use std::path::{Path, PathBuf};
use tpcdsgen::config::{Session, Table};
use tpcdsgen::row::*;

type Result<T> = std::result::Result<T, Box<dyn std::error::Error>>;

/// Return the output path for `table`'s file, following `tpchgen-cli`'s
/// `--parts`/`--part` naming convention:
///
/// When `--parts` was not requested creates a single `<table>.<ext>` file, otherwise
/// written into a subdirectory like `<table>/<table>.<chunk>.<ext>`.
///
/// Note that `--parts 1` is also written to a subdirectory.
///
/// This function creates the per-table subdirectory as needed.
pub(super) fn output_path(
    output_dir: &Path,
    table: Table,
    ext: &str,
    session: &Session,
) -> io::Result<PathBuf> {
    // sub directory `<table>/<table>.<chunk>.<ext>`
    if session.is_partitioned() {
        let dir = output_dir.join(table.get_name());
        std::fs::create_dir_all(&dir)?;
        Ok(dir.join(format!(
            "{}.{}.{ext}",
            table.get_name(),
            session.get_chunk_number()
        )))
    } else {
        // single `<table>.<ext>` file
        Ok(output_dir.join(format!("{}.{ext}", table.get_name())))
    }
}

/// The output file for one table.
pub(super) trait TableWriter {
    /// Write one generated row.
    fn write_row(&mut self, row: &GeneratedRow) -> io::Result<()>;

    /// Flush and finalize the file, returning the path it was written to.
    fn finish(self) -> Result<PathBuf>;
}

/// An output format: creates the per-table writers.
pub(super) trait TableOutput {
    type Writer: TableWriter;

    /// Create the output file for `table`, ready to accept rows.
    fn create_writer(&self, table: Table, session: &Session) -> Result<Self::Writer>;
}

/// Trait for creating row generators.
pub(super) trait RowGeneratorFactory: RowGenerator + Sized {
    fn create() -> Self;
}

macro_rules! impl_factory {
    ($($gen:ty),*) => {
        $(
            impl RowGeneratorFactory for $gen {
                fn create() -> Self { Self::new() }
            }
        )*
    };
}

// Implement factory for all simple generators
impl_factory!(
    CallCenterRowGenerator,
    CatalogPageRowGenerator,
    CustomerRowGenerator,
    CustomerAddressRowGenerator,
    CustomerDemographicsRowGenerator,
    DateDimRowGenerator,
    DbgenVersionRowGenerator,
    HouseholdDemographicsRowGenerator,
    IncomeBandRowGenerator,
    InventoryRowGenerator,
    ItemRowGenerator,
    PromotionRowGenerator,
    ReasonRowGenerator,
    ShipModeRowGenerator,
    StoreRowGenerator,
    TimeDimRowGenerator,
    WarehouseRowGenerator,
    WebPageRowGenerator,
    WebSiteRowGenerator
);

// Implement factory for generators that emit sales and returns rows
impl_factory!(
    CatalogSalesRowGenerator,
    StoreSalesRowGenerator,
    WebSalesRowGenerator
);

/// Generate one requested table into `output`.
pub(super) fn generate_table<O: TableOutput>(
    output: &O,
    table: Table,
    session: &Session,
    progress: ProgressHandle,
) -> Result<()> {
    macro_rules! generate {
        ($GENERATOR:ty) => {
            generate_rows::<$GENERATOR, O>(output, table, session, progress)
        };
    }

    match table {
        // Simple dimension tables
        Table::CallCenter => generate!(CallCenterRowGenerator),
        Table::CatalogPage => generate!(CatalogPageRowGenerator),
        Table::Customer => generate!(CustomerRowGenerator),
        Table::CustomerAddress => generate!(CustomerAddressRowGenerator),
        Table::CustomerDemographics => generate!(CustomerDemographicsRowGenerator),
        Table::DateDim => generate!(DateDimRowGenerator),
        Table::DbgenVersion => generate!(DbgenVersionRowGenerator),
        Table::HouseholdDemographics => generate!(HouseholdDemographicsRowGenerator),
        Table::IncomeBand => generate!(IncomeBandRowGenerator),
        Table::Inventory => generate!(InventoryRowGenerator),
        Table::Item => generate!(ItemRowGenerator),
        Table::Promotion => generate!(PromotionRowGenerator),
        Table::Reason => generate!(ReasonRowGenerator),
        Table::ShipMode => generate!(ShipModeRowGenerator),
        Table::Store => generate!(StoreRowGenerator),
        Table::TimeDim => generate!(TimeDimRowGenerator),
        Table::Warehouse => generate!(WarehouseRowGenerator),
        Table::WebPage => generate!(WebPageRowGenerator),
        Table::WebSite => generate!(WebSiteRowGenerator),

        // A sales generator emits rows for its sales table and its returns
        // table. Each of the two is its own output, generated by walking the
        // same generator and keeping only that table's rows -- the same way
        // the Arrow generators produce them.
        Table::StoreSales | Table::StoreReturns => generate!(StoreSalesRowGenerator),
        Table::CatalogSales | Table::CatalogReturns => generate!(CatalogSalesRowGenerator),
        Table::WebSales | Table::WebReturns => generate!(WebSalesRowGenerator),

        // Source tables - skip
        _ => Ok(()),
    }
}

/// Generate the rows for `table`
///
/// Progress is counted in source rows; see [`super::progress::register_table`]
fn generate_rows<G: RowGeneratorFactory, O: TableOutput>(
    output: &O,
    table: Table,
    session: &Session,
    progress: ProgressHandle,
) -> Result<()> {
    let source_row_range = session.get_source_row_range(table);
    // An empty chunk of a partitioned run has no rows and so no file; an
    // empty unpartitioned table still gets its (empty) file.
    if source_row_range.is_empty() && session.is_partitioned() {
        progress.complete();
        return Ok(());
    }

    let mut generator = G::create();
    generator.skip_rows_until_starting_row_number(*source_row_range.start());
    let last_row_number = *source_row_range.end();

    let mut writer = output.create_writer(table, session)?;

    info!("Generating {}...", table.get_name());

    let mut generated_rows = 0u64;
    let mut row_number = *source_row_range.start();

    while row_number <= last_row_number {
        let result = generator.generate_row_and_child_rows(row_number, session, None, None)?;
        let (rows, should_end_row) = result.into_parts();

        for row in rows {
            if row.table() == table {
                writer.write_row(&row)?;
                generated_rows += 1;
            }
        }

        if should_end_row {
            generator.consume_remaining_seeds_for_row();
            row_number += 1;
            progress.increment(1);
        }
    }

    let path = writer.finish()?;
    progress.complete();
    info!(
        "Generated {}: {} rows -> {}",
        table.get_name(),
        generated_rows,
        path.display()
    );

    Ok(())
}
