[package]
name = "tpchgen-arrow"
version = "3.0.0"
edition = "2024"
authors = ["clflushopt", "alamb"]
description = "TPC-H data generator into Apache Arrow format"
repository = { workspace = true }
readme = "README.md"
license = "Apache-2.0"

[dependencies]
arrow = { workspace = true }
tpchgen = { path = "../tpchgen", version = "3.0.0" }

[dev-dependencies]
arrow-csv = { workspace = true }
chrono = "0.4.39"
