name: tpchgen-cli-publish-pypi

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-packages.yml

  release:
    name: Release
    runs-on: ubuntu-latest
    environment: pypi
    needs: [build]
    permissions:
      id-token: write # Use to sign the release artifacts and for pypi trusted publishing
      attestations: write # Used to generate artifact attestation
    steps:
      - uses: actions/download-artifact@v4

      - name: Install twine
        run: pip install twine

      - name: Check distributions with twine
        run: twine check --strict wheels-*/*

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: 'wheels-*/*'

      - name: Publish to PyPI
        uses: PyO3/maturin-action@v1
        with:
          command: upload
          args: --non-interactive --skip-existing wheels-*/*
